[package]
name = "dockerprac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-web = "4.3.1"
anyhow = "1.0.71"
dotenvy = "0.15.7"
env_logger = "0.10.0"
log = "0.4.19"
serde = { version = "1.0.164", features = ["derive"] }
sqlx = { version = "0.6.3", features = ["runtime-actix-rustls", "postgres", "uuid"] }
uuid = { version = "1.4.0", features = ["v4", "serde"] }
