// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export interface DBPostAndUser { msg: string, user: User, likes: number, ts: string, id: string, }