// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DBReply { usr: string | null, content: string | null, ts: string | null, likes: bigint | null, id: bigint | null, path: string | null, }