// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Message { usr: string, content: string, ts: string, likes: bigint, path: string | null, }