// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Post { msg: string, user: string, likes: number, ts: string, id: string, }