// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Reply { userid: string, msgid: string, content: string, ts: string, likes: bigint, id: string, children: Array<string>, }