// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ReplyMessage { id: bigint, content: string, usr: string, path: string | null, }