// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Post } from "./Post";
import type { User } from "./User";

export type UserAndPost = { user: User; post: Post };

