// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DBPost } from "./DBPost";
import type { User } from "./User";

export interface UserAndPost { user: User, post: DBPost, }